---
name: n8n
services:
  n8nio:
    image: docker.n8n.io/n8nio/n8n:1.119.1
    container_name: n8n
    volumes:
      - ./data:/home/node/.n8n
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.rule=Host(`n8n.local.jstockley.com`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=production
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    restart: unless-stopped
