---
name: web-scraper
services:
  web-scraper-hyundai:
    image: jnstockley/web-scraper:v1.0.3
    container_name: web_scraper_hyundai
    volumes:
      - ./hyundai-data/:/app/data/
    environment:
      - TZ=America/Chicago
      - SCRAPER=diff
      - URL=https://update.hyundai.com/US/EN/updateNoticeList
      - PERCENTAGE=5
      - SLEEP_TIME_SEC=21600
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: python src/healthcheck.py || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    security_opt:
      - no-new-privileges:true
